spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd-ticketera
    username: root
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ticketerasoporte@gmail.com
    password: Prueba123unla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
